name: memories
description: Memories
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # state management
  flutter_bloc_side_effect: ^0.0.2
  bloc_concurrency: ^0.2.5

  # navigation
  go_router: ^14.3.0

  # persistence
  drift: ^2.20.3
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  sqlite3_flutter_libs: ^0.5.24

  # utils
  device_info_plus: ^11.0.0
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.1
  logger: ^2.4.0
  package_info_plus: ^8.0.3
  permission_handler: ^11.3.1
  theme_tailor: ^3.0.1
  email_validator: ^3.0.0
  jwt_decoder: ^2.0.1
  flutter_cache_manager: ^3.4.1
  pdf_render: ^1.4.12

  # http
  dio: ^5.7.0
  retrofit: ^4.4.1
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_db_store: ^5.1.1

  # localization
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  # fonts
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  webview_flutter: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.2
  dart_code_metrics_presets: ^2.16.0

flutter_intl:
  enabled: true
  output_dir: lib/app/localization/generated
  arb_dir: lib/app/localization

# fluttergen -c pubspec.yaml
flutter_gen:
  output: lib/app/values/
  line_length: 80

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - .configs/prod/
    - .configs/dev/